import type { PowerCardDef, PowerCardId } from "@/types/game";

const art = (id: PowerCardId) => `/assets/power-cards/${id}.webp`;

export const POWER_CARDS: PowerCardDef[] = [
  {
    id: "oeil_sorcier",
    name: "Œil du Sorcier",
    category: "offensive",
    icon: "eye",
    tone: "pink",
    rarity: "rare",
    targetMode: "opponent",
    art: art("oeil_sorcier"),
    activationTitle: "VISION",
    activationText: "Main adverse révélée",
    description: "Vois la main d'un adversaire pendant 5 secondes.",
    costCauris: 30,
    costFcfa: 500,
  },
  {
    id: "pluie_etoiles",
    name: "Pluie d'Étoiles",
    category: "score",
    icon: "sparkle",
    tone: "gold",
    rarity: "rare",
    targetMode: "none",
    art: art("pluie_etoiles"),
    activationTitle: "PLUIE D'OR",
    activationText: "+200 FCFA dans le pot",
    description: "+200 FCFA bonus au pot si tu remportes ce pli.",
    costCauris: 50,
    costFcfa: 800,
  },
  {
    id: "vent_nord",
    name: "Vent du Nord",
    category: "perturbation",
    icon: "wind",
    tone: "teal",
    rarity: "common",
    targetMode: "none",
    art: art("vent_nord"),
    activationTitle: "VENT LEVÉ",
    activationText: "Ta plus faible carte change",
    description: "Échange une carte faible de ta main contre une carte de la pioche.",
    costCauris: 25,
    costFcfa: 400,
  },
  {
    id: "benediction_chef",
    name: "Bénédiction du Chef",
    category: "score",
    icon: "star",
    tone: "gold",
    rarity: "epic",
    targetMode: "none",
    art: art("benediction_chef"),
    activationTitle: "BÉNÉDICTION",
    activationText: "Gain du pli x2",
    description: "Double le gain si tu remportes ce pli.",
    costCauris: 35,
    costFcfa: 600,
  },
  {
    id: "coupe_circuit",
    name: "Coupe-Circuit",
    category: "offensive",
    icon: "cut",
    tone: "pink",
    rarity: "rare",
    targetMode: "opponent",
    art: art("coupe_circuit"),
    activationTitle: "COUPÉ !",
    activationText: "La cible jouera bas",
    description: "Force un adversaire à jouer sa carte légale la plus faible.",
    costCauris: 40,
    costFcfa: 700,
  },
  {
    id: "sable_temps",
    name: "Sable du Temps",
    category: "perturbation",
    icon: "hourglass",
    tone: "teal",
    rarity: "rare",
    targetMode: "opponent",
    art: art("sable_temps"),
    activationTitle: "TEMPS FIGÉ",
    activationText: "Timer adverse gelé",
    description: "Gèle le timer d'un adversaire pendant 10 secondes.",
    costCauris: 30,
    costFcfa: 500,
  },
  {
    id: "bouclier_village",
    name: "Bouclier du Village",
    category: "defense",
    icon: "crown",
    tone: "teal",
    rarity: "epic",
    targetMode: "self",
    art: art("bouclier_village"),
    activationTitle: "BOUCLIER",
    activationText: "La prochaine attaque ciblée est bloquée",
    description: "Bloque la prochaine carte offensive ciblée contre toi.",
    costCauris: 55,
    costFcfa: 900,
  },
  {
    id: "tambour_appel",
    name: "Tambour d'Appel",
    category: "tactical",
    icon: "sound",
    tone: "gold",
    rarity: "common",
    targetMode: "self",
    art: art("tambour_appel"),
    activationTitle: "TAMBOUR",
    activationText: "+8 secondes",
    description: "Ajoute 8 secondes à ton timer ce tour.",
    costCauris: 22,
    costFcfa: 350,
  },
  {
    id: "cauris_chanceux",
    name: "Cauris Chanceux",
    category: "economy",
    icon: "coin",
    tone: "gold",
    rarity: "common",
    targetMode: "self",
    art: art("cauris_chanceux"),
    activationTitle: "CHANCE",
    activationText: "Remboursement si tu perds",
    description: "Récupère 50% de ta mise si tu perds la manche.",
    costCauris: 28,
    costFcfa: 450,
  },
  {
    id: "main_griot",
    name: "Main du Griot",
    category: "tactical",
    icon: "profile",
    tone: "teal",
    rarity: "rare",
    targetMode: "self",
    art: art("main_griot"),
    activationTitle: "CONSEIL",
    activationText: "Meilleure carte suggérée",
    description: "Suggère ta meilleure carte légale pendant 6 secondes.",
    costCauris: 32,
    costFcfa: 520,
  },
  {
    id: "eclair_mfoundi",
    name: "Éclair du Mfoundi",
    category: "offensive",
    icon: "spark",
    tone: "teal",
    rarity: "epic",
    targetMode: "self",
    art: art("eclair_mfoundi"),
    activationTitle: "ÉCLAIR",
    activationText: "+2 sur ta prochaine carte",
    description: "Ta prochaine carte gagne +2 valeur virtuelle, max 10.",
    costCauris: 58,
    costFcfa: 950,
  },
  {
    id: "totem_ancetres",
    name: "Totem des Ancêtres",
    category: "defense",
    icon: "trophy",
    tone: "gold",
    rarity: "legendary",
    targetMode: "self",
    art: art("totem_ancetres"),
    activationTitle: "ANCESTRES",
    activationText: "Double pénalité protégée",
    description: "Protège du malus double si tu perds cette manche.",
    costCauris: 70,
    costFcfa: 1200,
  },
  {
    id: "masque_bluffeur",
    name: "Masque du Bluffeur",
    category: "defense",
    icon: "eye",
    tone: "pink",
    rarity: "rare",
    targetMode: "self",
    art: art("masque_bluffeur"),
    activationTitle: "BLUFF",
    activationText: "La prochaine lecture est annulée",
    description: "Annule la prochaine révélation ou lecture adverse contre toi.",
    costCauris: 38,
    costFcfa: 640,
  },
  {
    id: "filet_pecheur",
    name: "Filet du Pêcheur",
    category: "offensive",
    icon: "wind",
    tone: "teal",
    rarity: "rare",
    targetMode: "opponent",
    art: art("filet_pecheur"),
    activationTitle: "FILET",
    activationText: "La cible joue bas",
    description: "Force la cible à jouer sa plus basse carte légale.",
    costCauris: 42,
    costFcfa: 720,
  },
  {
    id: "marche_nuit",
    name: "Marché de Nuit",
    category: "tactical",
    icon: "coin",
    tone: "cobalt",
    rarity: "epic",
    targetMode: "self",
    art: art("marche_nuit"),
    activationTitle: "MARCHÉ",
    activationText: "Carte faible améliorée",
    description: "Remplace ta plus faible carte par une meilleure carte si la pioche le permet.",
    costCauris: 60,
    costFcfa: 1000,
  },
  {
    id: "cri_chef",
    name: "Cri du Chef",
    category: "perturbation",
    icon: "sound",
    tone: "pink",
    rarity: "rare",
    targetMode: "none",
    art: art("cri_chef"),
    activationTitle: "CRI DU CHEF",
    activationText: "-3s aux adversaires",
    description: "Si tu es leader du pli, retire 3 secondes aux adversaires.",
    costCauris: 36,
    costFcfa: 580,
  },
  {
    id: "feu_camp",
    name: "Feu de Camp",
    category: "score",
    icon: "spark",
    tone: "gold",
    rarity: "common",
    targetMode: "none",
    art: art("feu_camp"),
    activationTitle: "FEU ALLUMÉ",
    activationText: "+100 FCFA au pot",
    description: "+100 FCFA au pot si tu domines ce pli.",
    costCauris: 24,
    costFcfa: 380,
  },
  {
    id: "pagne_changeant",
    name: "Pagne Changeant",
    category: "tactical",
    icon: "cards",
    tone: "cobalt",
    rarity: "legendary",
    targetMode: "self",
    art: art("pagne_changeant"),
    activationTitle: "CAMÉLÉON",
    activationText: "Ta prochaine carte suit la tendance",
    description: "Ta prochaine carte hors tendance compte comme tendance si tu n'as pas la couleur.",
    costCauris: 72,
    costFcfa: 1250,
  },
];

export const POWER_CARDS_BY_ID: Record<PowerCardId, PowerCardDef> = Object.fromEntries(
  POWER_CARDS.map((c) => [c.id, c]),
) as Record<PowerCardId, PowerCardDef>;

export const MAX_EQUIPPED_POWERS = 3;

export const CAURIS_REWARDS = {
  perWin: 20,
  perTrick: 2,
  dailyChallenge: 50,
} as const;

export const STARTING_CAURIS = 50;
